image:
  repository: ghcr.io/rskaradag/rsk-app
  tag: latest
  pullPolicy: Always

postgresql:
  user: postgres
  database: tasksdb

service:
  type: NodePort
  port: 80
  nodePort: 30080
  
ingress:
  enabled: true
  host: rsk-app.local

resources: {}