apiVersion: v1
kind: Service
metadata:
  name: rsk-app
  namespace: {{ .Release.Namespace }}
  labels:
    app: rsk-app
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: rsk-app
  ports:
    - port: 80
      targetPort: 5000
  type: ClusterIP