apiVersion: v1
kind: Service
metadata:
  name: rsk-app-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: rsk-app
spec:
  type: ClusterIP
  selector:
    app: rsk-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000 