apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsk-app
  namespace: {{ .Release.Namespace }}
  labels:
    app: rsk-app
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsk-app
  template:
    metadata:
      labels:
        app: rsk-app
    spec:
      containers:
        - name: rsk-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: rsk-config
                  key: DATABASE_URL
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"