name: CI/CD for rsk-app with Multi-Arch Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Multi-Arch Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-arch Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./rsk-app
          file: ./rsk-app/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/rskaradag/rsk-app:latest